### ISSUE TITLE
setup database in docker.

### ISSUE THREAD

**Issue by 4geru** [4geru/kotlin-todo-app#2]

**Comment by sh-ogawa** [comment]
```yaml
services:
  db:
    container_name: sample-db
    image: 8.3.0
    restart: always
    ports:
      - "13306:3306"
    volumes:
      - ./docker/db/ddl:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
      - db_log:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
```
